flowchart TD
    A[VALIDASI DOKUMEN PERSYARATAN ADMINISTRASI] --> B{Apakah seluruh berkas lengkap dan memenuhi ketentuan?}
    B -->|lengkap| C(Penerbitan Surat Keterangan)
    B -->|tidak lengkap| D[Pengembalian berkas ke pemohon]
    C --> E((OK))
