---
config:
  sankey:
    showValues: true
    nodeAlignment: justify
    linkColor: gradient
    suffix: " TWh"
---
sankey-beta

%% Where a country's primary energy ends up.
Coal,Electricity,42
Gas,Electricity,31
Gas,Heating,18
Nuclear,Electricity,25
Wind,Electricity,17
Solar,Electricity,9
Electricity,Industry,48
Electricity,Homes,40
Electricity,Losses,36
Heating,Homes,12
Heating,"Industry, light",6
